
# This is a Terragrunt unit generated by Gruntwork Boilerplate (https://github.com/gruntwork-io/boilerplate).
terraform {
  source = "../../../modules/network"
}

include "root" {
  path = find_in_parent_folders("root.hcl")
}

inputs = {
  # --------------------------------------------------------------------------------------------------------------------
  # Required input variables
  # --------------------------------------------------------------------------------------------------------------------

  # Description: Name of the VPC. Every resource in this module is named after it.
  # Type: string
  name = "dev"

  # Description: IPv4 CIDR block for the VPC, e.g. 10.0.0.0/16.
  # Type: string
  cidr_block = "10.0.0.0/16"


  # --------------------------------------------------------------------------------------------------------------------
  # Optional input variables
  # Uncomment the ones you wish to set
  # --------------------------------------------------------------------------------------------------------------------

  # Description: Availability zones to spread subnets across. One public and one private subnet is created per AZ.
  # Type: list
  azs = ["eu-west-2a", "eu-west-2b"]

  # Description: Whether to create a NAT gateway so private subnets can reach the internet.
  # Type: bool
  # enable_nat_gateway = false

  # Description: Tags applied to every resource in this module.
  # Type: map
  # tags = {}

}
