# Generated by `terragrunt scaffold` using the app-service module's own .boilerplate template.
#
# Everything below - the dependency wiring, the mock outputs, the tag merge - is house style
# the built-in template has no way to know about. Encode it once here and every unit anyone
# ever scaffolds from this module gets it for free.
terraform {
  source = "../../../modules/app-service"
}

include "root" {
  path   = find_in_parent_folders("root.hcl")
  expose = true
}

locals {
  team = "platform"
}

# This service always needs a VPC and subnets, and they always come from a network unit.
# The template knows that, so you never write this block by hand.
dependency "network" {
  config_path = "../network"

  mock_outputs = {
    vpc_id     = "vpc-mock"
    subnet_ids = ["subnet-mock-a", "subnet-mock-b"]
  }
  mock_outputs_allowed_terraform_commands = ["validate", "plan", "init", "destroy"]
}

inputs = {
  # --------------------------------------------------------------------------------------------------------------------
  # Required input variables
  # --------------------------------------------------------------------------------------------------------------------

  # Name of the service. Used for the task definition, log group and load balancer target group.
  # Type: string
  service_name = "api"

  # Container image to run, including tag, e.g. ghcr.io/acme/api:v1.4.2.
  # Type: string
  image = "ghcr.io/acme/api:v1.4.2"

  # Wired to the network unit by the template.
  vpc_id = dependency.network.outputs.vpc_id

  # Wired to the network unit by the template.
  subnet_ids = dependency.network.outputs.subnet_ids


  # --------------------------------------------------------------------------------------------------------------------
  # Optional input variables
  # Uncomment the ones you wish to set
  # --------------------------------------------------------------------------------------------------------------------

  # Number of tasks to run.
  # Type: number
  # desired_count = 2

  # CPU units to reserve per task. 1024 units is one vCPU.
  # Type: number
  # cpu = 256

  # Memory in MiB to reserve per task.
  # Type: number
  # memory = 512

  # Port the container listens on.
  # Type: number
  # container_port = 8080

  # HTTP path the load balancer polls to decide whether a task is healthy.
  # Type: string
  # health_check_path = "/healthz"

  # Environment variables to pass to the container.
  # Type: map
  environment_variables = {
    LOG_LEVEL = "debug"
  }

  # How long to keep container logs for.
  # Type: number
  # log_retention_days = 30

  # Merged with the shared tags from root.hcl rather than replacing them.
  tags = merge(include.root.inputs.tags, {
    Owner = local.team
  })

}
