# Generated by `terragrunt scaffold` using the house template at templates/terragrunt-unit.
#
# This module does not ship a .boilerplate/ directory of its own, so it inherits the
# organisation default. Editing this one file changes what every such module scaffolds - no
# need to touch the modules themselves.
terraform {
  source = "{{ .sourceUrl }}"
}
{{ if .EnableRootInclude }}
include "root" {
  path   = find_in_parent_folders("{{ .RootFileName }}")
  expose = true
}
{{ end }}
locals {
  team = "{{ .TeamName }}"
}

inputs = {
  # --------------------------------------------------------------------------------------------------------------------
  # Required input variables
  # --------------------------------------------------------------------------------------------------------------------
{{ range .requiredVariables }}
  # {{ .Description }}
  # Type: {{ .Type }}
  {{- if .UserValue }}
  {{ .Name }} = {{ .UserValue }}
  {{- else }}
  {{ .Name }} = {{ .DefaultValuePlaceholder }}  # TODO: fill in value
  {{- end }}
{{ end }}
  # --------------------------------------------------------------------------------------------------------------------
  # Optional input variables
  # Uncomment the ones you wish to set
  # --------------------------------------------------------------------------------------------------------------------
{{ range .optionalVariables }}
{{- if eq .Name "tags" }}
  # House rule: always merge with the shared tags, never replace them.
  tags = merge(include.root.inputs.tags, {
    Owner = local.team
  })
{{ else }}
  # {{ .Description }}
  # Type: {{ .Type }}
  {{ if .UserValue }}{{ .Name }} = {{ .UserValue }}{{ else }}# {{ .Name }} = {{ .DefaultValue }}{{ end }}
{{ end }}
{{- end }}
}
