# Generated by `terragrunt scaffold` using the app-service module's own .boilerplate template.
#
# Everything below - the dependency wiring, the mock outputs, the tag merge - is house style
# the built-in template has no way to know about. Encode it once here and every unit anyone
# ever scaffolds from this module gets it for free.
terraform {
  source = "{{ .sourceUrl }}"
}
{{ if .EnableRootInclude }}
include "root" {
  path   = find_in_parent_folders("{{ .RootFileName }}")
  expose = true
}
{{ end }}
locals {
  team = "{{ .TeamName }}"
}

# This service always needs a VPC and subnets, and they always come from a network unit.
# The template knows that, so you never write this block by hand.
dependency "network" {
  config_path = "{{ .DependencyPath }}"

  mock_outputs = {
    vpc_id     = "vpc-mock"
    subnet_ids = ["subnet-mock-a", "subnet-mock-b"]
  }
  mock_outputs_allowed_terraform_commands = ["validate", "plan", "init", "destroy"]
}

inputs = {
  # --------------------------------------------------------------------------------------------------------------------
  # Required input variables
  # --------------------------------------------------------------------------------------------------------------------
{{ range .requiredVariables }}
{{- if eq .Name "vpc_id" }}
  # Wired to the network unit by the template.
  vpc_id = dependency.network.outputs.vpc_id
{{ else if eq .Name "subnet_ids" }}
  # Wired to the network unit by the template.
  subnet_ids = dependency.network.outputs.subnet_ids
{{ else }}
  # {{ .Description }}
  # Type: {{ .Type }}
  {{- if .UserValue }}
  {{ .Name }} = {{ .UserValue }}
  {{- else }}
  {{ .Name }} = {{ .DefaultValuePlaceholder }}  # TODO: fill in value
  {{- end }}
{{ end }}
{{- end }}

  # --------------------------------------------------------------------------------------------------------------------
  # Optional input variables
  # Uncomment the ones you wish to set
  # --------------------------------------------------------------------------------------------------------------------
{{ range .optionalVariables }}
{{- if eq .Name "tags" }}
  # Merged with the shared tags from {{ $.RootFileName }} rather than replacing them.
  tags = merge(include.root.inputs.tags, {
    Owner = local.team
  })
{{ else }}
  # {{ .Description }}
  # Type: {{ .Type }}
  {{ if .UserValue }}{{ .Name }} = {{ .UserValue }}{{ else }}# {{ .Name }} = {{ .DefaultValue }}{{ end }}
{{ end }}
{{- end }}
}
